### ISSUE TITLE
[Yelp Reviews API] Empty Response for All Requests

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1398]
A high volume customer noticed that Yelp Reviews API currently seems to be returning empty responses for `place_id`s that should return reviews. This includes our Playground example:

<img width="1398" alt="Screenshot 2024-02-07 at 12 04 45 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/216a592d-88db-4d0e-8625-a7f4e43ae3d7">

<img width="1396" alt="Screenshot 2024-02-07 at 12 05 31 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/7946eaca-80ab-46e2-bcc0-1844e28abcbd">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000058600?view=List) | [Playground](https://serpapi.com/playground?engine=yelp_reviews&place_id=MGzro82Fi4LYvc86acoONQ) | [Inspector](https://serpapi.com/searches/65c3e1869f55b348e57efa3c/inspect)

**Comment by schaferyan** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000058611?view=List)

**Comment by Hudson6124** [comment]
Hey, is there any update on this?

**Comment by tanys123** [comment]
Hi @Hudson6124, we are working on a fix, and it is being reviewed. We will update you once it is deployed.

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059063?view=List)

**Comment by schaferyan** [comment]
An Enterprise Customer reported this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059196?view=List)

**Comment by schaferyan** [comment]
A customer followed up:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059624?view=List)

**Comment by tanys123** [comment]
We have released a fix for [Yelp Reviews API](https://serpapi.com/playground?engine=yelp_reviews). Do note that only IDs like `ED7A7vDdg8yLNKJTSVHHmg` could work after this update. We have also added new parameters, `rating` and `num`. Check out the [documentation](https://serpapi.com/yelp-reviews-api) for more details.

<img width="1450" alt="Screenshot 2024-02-22 at 5 02 32 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/8d623c97-7492-4c2e-ab21-3edb8ff06385">

**Comment by Hudson6124** [comment]
Great to hear! Thanks for letting me know. With the bum param, is a
“result” a single review? So if I set to “50”, I’d get 50 reviews back? If
so- that’s a great update and thank you.

**Comment by tanys123** [comment]
> Great to hear! Thanks for letting me know. With the bum param, is a “result” a single review? So if I set to “50”, I’d get 50 reviews back? If so- that’s a great update and thank you.

@Hudson6124 Yes, that's correct!

**Comment by hilmanski** [comment]
Let's reinvestigate this issue.
As a customer reported, this issue is back, and I'm able to replicate it.

Sample Yelp Search (to get a place_id): [Inspect](https://serpapi.com/searches/65e13ea379627c10992fa329/inspect)
Screenshot id is available
![CleanShot 2024-03-01 at 10 36 34](https://github.com/serpapi/public-roadmap/assets/4522467/373b7f84-262b-4dcf-9442-cf6fe67eb243)

Search on Yelp Reviews result error: [Inspect](https://serpapi.com/searches/65e13f092fe3021593735af7/inspect)

Other sample of failed searches:
- [Inspect](https://serpapi.com/searches/65e13dc9969c08be88228ac4/inspect)
- [Inspect](https://serpapi.com/searches/65e13c032bc7d8e5a5e44f50/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060192?view=List)

**Comment by schaferyan** [comment]
I believe this may be a different issue, as not all `place_id`'s are affected, whereas prior to this fix, all Yelp Reviews API requests were failing.

Adding an intercom link here for a customer who was affected by the fix. Their issue is that they have been using the human-readable `place_id`, but we should keep them updated in case the new problem @hilmanski mentioned above affects them as well.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060270?view=List)

**Comment by tanys123** [comment]
We have deployed a potential fix to the issues where some `place_id` was getting empty responses. We will keep an eye on the performance.

**Comment by Hudson6124** [comment]
Hey, I am still getting errors for many place ids. For example, these are some that are not working for me:

_N9k6eQy1UEOecPLuoVq6A
puPHD6sAnx8ZpfOHVVRDOA
TomTVvSUh5Trw2Pcu8Orvw

Amongst others

**Comment by tanys123** [comment]
@Hudson6124 Got it, thanks for reporting the issue.

I am able to retrieve the result from the place ids you have provided. However, I am aware of the underlying issue where it sometimes fails. I'll look into the issue and update you when we deploy a fix. Thanks.

<img width="1266" alt="Screenshot 2024-03-05 at 9 49 27 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/b1b245a8-7db7-466d-81ac-015849a7e656">
<img width="1260" alt="Screenshot 2024-03-05 at 9 49 32 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/563a3356-4524-432f-9858-30a0f0c9da6d">
<img width="1263" alt="Screenshot 2024-03-05 at 9 49 38 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/fe4e542d-e2b6-4623-83ba-66a79db627df">

**Comment by tanys123** [comment]
We have seen stable performance after the last deployment. Feel free to reopen if you face an issue.
