### ISSUE TITLE
[Google Maps Reviews API] Valid Searches Return Empty Results Most of the Time

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1515]
A high volume customer reported the Google Maps Reviews API is sometimes returning empty results for searches that should return reviews. 

I've been able to replicate this in the Playground. When retrying the same valid search with `no_cache=true`, it seems to return the expected result about 2/10 times. The other 8/10 times it returns the `"reviews_results_state":
"Fully empty"` response.  

I replicated this behavior with our Playground example, and two examples the customer shared.

This may or may not be related to https://github.com/serpapi/public-roadmap/issues/970, as in the instance reported there the `no_reviews` response was returned rather than `fully_empty`.

<img width="1414" alt="Screenshot 2024-03-28 at 10 46 00 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/2376f2f1-616f-4dce-9637-b8c742124856">

[Inspector ](https://serpapi.com/searches/6605af5b3c3fb276e641b3bc/inspect)| [Inspector](https://serpapi.com/searches/6605af5447ccf13efabc9695/inspect) | [Inspector](https://serpapi.com/searches/6605ae991e803fe36e7f4251/inspect) | [Playground](https://serpapi.com/playground?engine=google_maps_reviews&data_id=0x151b6176dd1bfe6b%3A0x109b2f979c4a222b&hl=en&sort_by=newestFirst&no_cache=true) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062336?view=List)

**Comment by schaferyan** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062339?view=List)

**Comment by schaferyan** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062361?view=List)

**Comment by wilsonowilson** [comment]
We're experiencing this issue right now and our customers are very unhappy :(

**Comment by kagermanov27** [comment]
We have deployed a fix for this.
@wilsonowilson, we apologize for any inconvenience. We are grateful to the reporting customers and ready to take care of any issue they may face in the future.

Before:
![image](https://github.com/serpapi/public-roadmap/assets/73674035/26c10ecb-26ec-45ca-a1d8-a415512caeeb)

After:
<img width="1457" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/0e0eff8e-5334-4dab-a10d-6865bc78c460">

**Comment by kagermanov27** [comment]
The empty results rate decreased sometime after https://github.com/serpapi/SerpApi/pull/4697 was merged.

**Comment by matthewsewell** [comment]
Thanks. I'm still seeing empty results. Is this due to a propagation lag, caching, or some such thing?

**Comment by hilmanski** [comment]
Another customer reported this issue.

[Intrcom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062372?view=List)

**Comment by aakashbohara** [comment]
i am facing the same issue, no reviews: {"error":"An error occurred: 'reviews'"}

**Comment by aakashbohara** [comment]
I am still having the problem
[image: Screenshot (264).png]

**Comment by tanys123** [comment]
Hi @aakashbohara, can you share the Search ID or your search query for us to check?

**Comment by aakashbohara** [comment]
> Hi @aakashbohara, can you share the Search ID or your search query for us to check?

 extended_reviews = []
            params = {
                "engine": "google_maps_reviews",
                "place_id": place_id,
                "api_key": api,
                "sort_by": "ratingHigh",
                "num": 10
            }

            search = GoogleSearch(params)
            results = search.get_dict()
            serpreviews = results["reviews"]
            # total_reviews = results['place_info']['reviews']
            average_google_rating = results['place_info']['rating']
            next_page_token = results['serpapi_pagination']['next_page_token'] if 'serpapi_pagination' in results and 'next_page_token' in results['serpapi_pagination'] else ''
            print(next_page_token)

            user_reviews = {}
            for review_data in serpreviews:
                if "images" in review_data:
                    user_name = review_data["user"]["name"]
                    if user_name not in user_reviews:
                        user_reviews[user_name] = []
                    review = {
                        "review_link": review_data["link"],
                        "snippet": review_data["snippet"],
                        "rating": review_data["rating"],
                        "images": review_data["images"],
                        "date": review_data["date"],
                        "name": review_data["user"]["name"],
                        "link": review_data["user"]["link"],
                        "thumbnail": review_data["user"]["thumbnail"]
                    }
                    user_reviews[user_name].append(review)
                    extended_reviews.append(review)

**Comment by tanys123** [comment]
@aakashbohara Thanks for the info. Can you try adding `"no_cache": True` to the `params`, it might be serving the cache result.
In addition, It would be great if you could provide the `place_id` so that I can try to replicate it.

**Comment by aakashbohara** [comment]
place_id

> @aakashbohara Thanks for the info. Can you try adding `"no_cache": True` to the `params`, it might be serving the cache result. In addition, It would be great if you could provide the `place_id` so that I can try to replicate it.

place_id = 'ChIJSxekugccVIgRYQwo39Jk9rY'
after adding "no_cache": True
i got a different error: {"error":"An error occurred: 'place_info'"}

extended_reviews = []
            params = {
                "engine": "google_maps_reviews",
                "place_id": place_id,
                "api_key": api,
                "sort_by": "ratingHigh",
                "num": 10,
                "no_cache": True
            }

            search = GoogleSearch(params)
            results = search.get_dict()
            serpreviews = results["reviews"]
            # total_reviews = results['place_info']['reviews']
            average_google_rating = results['place_info']['rating']
            next_page_token = results['serpapi_pagination']['next_page_token'] if 'serpapi_pagination' in results and 'next_page_token' in results['serpapi_pagination'] else ''
            print(next_page_token)

            user_reviews = {}
            for review_data in serpreviews:
                if "images" in review_data:
                    user_name = review_data["user"]["name"]
                    if user_name not in user_reviews:
                        user_reviews[user_name] = []
                    review = {
                        "review_link": review_data["link"],
                        "snippet": review_data["snippet"],
                        "rating": review_data["rating"],
                        "images": review_data["images"],
                        "date": review_data["date"],
                        "name": review_data["user"]["name"],
                        "link": review_data["user"]["link"],
                        "thumbnail": review_data["user"]["thumbnail"]
                    }
                    user_reviews[user_name].append(review)
                    extended_reviews.append(review)

**Comment by aakashbohara** [comment]
> place_info

what is the alternative for place_info

**Comment by aakashbohara** [comment]
> params

Got my solution thank you, seems like there is no "place_info" now.

**Comment by marm123** [comment]
Thanks for fixing that @tanys123 ! Do you think we'll be able to get the `place_info` somehow in the future (with a different endpoint for example)? One of our customers asked about it.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062398?view=List)
