### ISSUE TITLE
[Google Flights API] No results on our API

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1656]
A customer reported that their search shows empty result on our API, when it's actually available on Google Flights. I can confirm this issue.

Actual Google Flight result -> [here](https://www.google.com/travel/flights?q=Flights+to+PQC+from+DLI+on+2024-06-26+one-way).

[Playground](https://serpapi.com/playground?engine=google_flights&departure_id=DLI&arrival_id=PQC&gl=us&hl=en&currency=USD&type=2&outbound_date=2024-06-26&travel_class=1&show_hidden=true&adults=1&children=0&infants_in_seat=0&infants_on_lap=0&stops=2) | [Inspect](https://serpapi.com/searches/66613c59c47d3c52180bd24d/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067511?view=List)

**Comment by zyc9012** [comment]
It's the `X-Goog-Batchexecute-Bgr` HTTP header, which will be validated on Google's Side.

`X-Goog-Batchexecute-Bgr` composes Chrome major version (e.g. 125) and post body. Unmatched Chrome major version and post body will sometimes make Google return fewer or empty results.

Example curl request

```
curl 'https://www.google.com/_/TravelFrontendUi/data/travel.frontend.flights.FlightsFrontendService/GetShoppingResults?hl=en&gl=us' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36' \
  -H 'x-goog-batchexecute-bgr: [";5fu4-6PQAAZb7ogee-5fXCQq3vhsWd8mADQBEArZ1LRrcp0CEUnxu8LF-ouTElMW1zvBjndG_IlIpaRUFzzH-O5A2ULkrY_2JY9jWJ37HwAAADRPAAAAAnUBB2MAPq81VS7VBjBrp-ux7QZSoLv_Muer7Uq43V9F2Uk6B5xD_gWBT-0cXSS6KGF80UUkw7RWULRmVq6v4muWav19hASUJ0GjF1Irn_Qd4luEq9saA90apdZkL7R2cieeOgCd8W2LsLSqC8ZxlDVA13eyP7aXKK9xAW0mxcKUQqvEtbISlg3_YHOxBSrDuE94SV9tOxcWT7EMXC1SgJbO2wXswvE9brvzVNBGuFJnS8RtV4q_wdneXzUUPJUYJzOMp2mHeEntz8f6myeVoFP-VLfoRYelJ9vQ0OqGXo5eOws8mG_YE6-d02VTPS-PAI9h42MIkRVNAPKTKPlg5JHv16bwTkatLXz40Z7MkgF8mekD5lLYy1yqYlpQ170ZpQRWUL0VqR4RhHPh0H7-iTcoQJ5kdlI8pGC2p3pbajMB1AfNOi8U4Ik0v5UDX9ODumd54UA_zTmdeLSJNz3M7lSkeJVS-SEVBpB_ZybjrqK20Eu-hcPxeqR2kI7P-isbZw_izJIQCzkRxqHADoRUNuLlfAqyTJSO1nqvUudVHeszHw39ysNjvPw8Z73KuYO5WkuKKXSI0cWvrmE1fTmgRKgBjAskw3JwLnSu-9GcrckbCW6sBi4VCrtq0g5kpcRzOFFFYtVSBgCxkXVidD_qRm2S1YGKnDXP90Bu-6JdutXLK_iPGzfMxG1Hi8YDGi7qfp-xSgNOTTQxmmy2PkzwiwAau0ZlZtClMflHstCyQV3EX8dwiNWmyQSb0OMw4Pgr-y2lBg47qgysmZFxjkuLA6RhyPcjNSqLVgvRWB8vGzcbc01sIDKxmyJ7LPWxKodft4Gls-LO3iJbt0I0m_DLkZv1MHJsy4R7DQKX1W87PVhDVbzEr_oMaIdcOGIHQsiIqYVWQ9JF4Xd71KTrSUAyugYThmcGicOhiS-lCUmtd0htHBuHWw069R8dwhvdOQ7M4uPrdo5ZA_4t3qoIg5XjAviFN9fhgY13OR2kdKR4IM6ycMnnSqQdjo3sKC2sKRkohGQSyufuc-1OAUbWBVdhe9s462sN-M0rl7FtRNSXRlXAmEndYFGtbBnavR4MxPBT0g207LxU4uQJ-V5msUa05LLiZp9WRlnyHJwkf9T9wj5qXQhVqOHCr6E_a0CC-Du6CzUKUk9qwx7IaapPug5rVs8twN95Tu9ial3AlzjyJAHxPvLhMEjb1mfeDvwCciDFv51ndLsNi47c8P26RLjG6h3E0o-ymFUMHSb6yvHvcDwDoaRGKCJKbSMC1RU_0AzH8A1BTC1DqZ9GSo4KNZCoJLC-0IxEhr438ExZuBJoR6i14Pje_UM6PiUWF52epEb2O1u2Rd7-jRsljrh-3bmrBgYaXkDRTfMCWtcUom_VcYTk91mj4S1UqW6aRyQs3-ouBO8iO0Y3NUj6MO6jtyT9g7kA4GFlbcBzaIy7tnpnfHvRd8iFBAXVg6DQn1-c4Mq4iGPElk9G5ejP0stENIiVW9z1-QgQEHbxUJHh0-JMoJvz81_7W2-itT4X9pSy5JSCvKKIQUzAiufgxXKCLkzL16v5MV6MT1PNZj0AzFalHvCXLjBm3SGncs5czoKxS6xn4r5bJ0aQ2y6ld9H16Fr5FExQ7E0llIxavTeoaWFjsT8r-XJNF2DRNfUyyAU",null,null,17,null,null,null,0,"5"]' \
  -H 'x-goog-ext-259736195-jspb: ["en-US","US","USD",2,null,[-480],null,[[72446894,97495046,97554504]],7,[]]' \
  --data-raw 'f.req=%5Bnull%2C%22%5B%5B%5D%2C%5Bnull%2Cnull%2C2%2Cnull%2C%5B%5D%2C1%2C%5B1%2C0%2C0%2C0%5D%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2C%5B%5B%5B%5B%5B%5C%22DLI%5C%22%2C0%5D%5D%5D%2C%5B%5B%5B%5C%22PQC%5C%22%2C0%5D%5D%5D%2Cnull%2C2%2Cnull%2Cnull%2C%5C%222025-04-01%5C%22%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2C3%5D%5D%2Cnull%2Cnull%2Cnull%2C1%5D%2C0%2C0%2C0%2C1%5D%22%5D&'
```

**Comment by zyc9012** [comment]
We've released a fix for this. It's now returning the same result as the Google Flight page.

![image](https://github.com/user-attachments/assets/92799afb-61ab-4d34-8e56-924ad7f0c4b4)

**Comment by hilmanski** [comment]
Hi @zyc9012. 

Currently, I'm still seeing an empty result for this search: [Inspect](https://serpapi.com/searches/66baf4785809e732f5cc824b/inspect) | [Playground](https://serpapi.com/playground?engine=google_flights&departure_id=DLI&arrival_id=PQC&gl=us&hl=en&currency=USD&type=2&outbound_date=2024-08-14&travel_class=1&show_hidden=true&adults=1&children=0&infants_in_seat=0&infants_on_lap=0&stops=2)

While it's available on the Google Flights: 
![CleanShot 2024-08-13 at 13 54 06](https://github.com/user-attachments/assets/b6dce9c7-52d3-409c-a6b7-1409ab009526)

**Comment by zyc9012** [comment]
@hilmanski The playground link is actually incorrect. It's selecting "1 stop or fewer", but on the Google Flights the Stops filter is not on.
