### ISSUE TITLE
[Google Search API] `Latest posts from` section not scraped on Desktop and Mobile

### ISSUE THREAD

**Issue by mikemorcerf** [serpapi/public-roadmap#2596]
`Latest posts from` section is not being scraped on Desktop and Mobile.
In addition, on some Mobile examples, `Latest posts from` is returned under `top_stories[: carousel]`, which also causes the actual `Top stories` sections not to be scraped.

Playground links with Screenshots:

* ### [Desktop - Rowan Atkinson](https://serpapi.com/playground?q=Rowan+Atkinson&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+source+ijn+ie+oe+pws+ibp+rlz+as_sitesearch+interval+size+color+maxPrice)
![Image](https://github.com/user-attachments/assets/6366502f-33a4-4b85-84db-035420bab526)

* ### [Desktop - mr beast](https://serpapi.com/playground?q=mr+beast&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+source+ijn+ie+oe+pws+ibp+rlz+as_sitesearch+interval+size+color+maxPrice)
![Image](https://github.com/user-attachments/assets/2c112c8c-ae7e-4626-8720-218415fb8258)

* ### [Mobile - Rowan Atkinson](https://serpapi.com/playground?q=Rowan+Atkinson&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+source+ijn+ie+oe+pws+ibp+rlz+as_sitesearch+interval+size+color+maxPrice)
![Image](https://github.com/user-attachments/assets/1158da54-eac7-4aef-ade6-61cf78680b92)

* ### [Mobile - mr beast (returned in Top Stories & Top Stories not scraped)](https://serpapi.com/playground?q=mr+beast&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+source+ijn+ie+oe+pws+ibp+rlz+as_sitesearch+interval+size+color+maxPrice)
![Image](https://github.com/user-attachments/assets/0f7fe28b-3482-4d94-9fac-5266160896f2)

![Image](https://github.com/user-attachments/assets/2609f6cc-023f-4c40-bdae-1a73f6397f93)

**Comment by mikemorcerf** [comment]
Thanks for tagging it @tanys123. Since there are client reports about it I'm moving it from `freezer` to `queue`.

**Comment by vedovati-matteo** [comment]
We have released a fix for this

Before:

![Image](https://github.com/user-attachments/assets/2a18edd2-24fb-4262-9d1c-be89fe4382d0)

After:

![Image](https://github.com/user-attachments/assets/306cf7f9-7a48-4bd8-a812-fcbdcae4accf)

**Comment by hilmanski** [comment]
An enterprise customer reported that this issue is back. I can confirm this on our playground.

[Playground](https://serpapi.com/playground?q=elon+musk+tweet&gl=us&hl=en&device=desktop&highlight=latest_posts&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq+client+votes+site+ie+oe+pws+ibp+source+as_sitesearch+ijn+rlz+interval+size+color+maxPrice+as_dt+direct_link+as_eq+maxPrice%25252525252525252525EF%25252525252525252525BB%25252525252525252525BF%25252525252525252525E2%2525252525252525252580%252525252525252525258B%25252525252525252525EF%25252525252525252525BB%25252525252525252525BF+maxPrice%252525252525252525EF%252525252525252525BB%252525252525252525BF%252525252525252525E2%25252525252525252580%2525252525252525258B%252525252525252525EF%252525252525252525BB%252525252525252525BF+maxPrice%2525252525252525EF%2525252525252525BB%2525252525252525BF%2525252525252525E2%252525252525252580%25252525252525258B%2525252525252525EF%2525252525252525BB%2525252525252525BF+maxPrice%25252525252525EF%25252525252525BB%25252525252525BF%25252525252525E2%2525252525252580%252525252525258B%25252525252525EF%25252525252525BB%25252525252525BF+maxPrice%252525252525EF%252525252525BB%252525252525BF%252525252525E2%25252525252580%2525252525258B%252525252525EF%252525252525BB%252525252525BF+maxPrice%2525252525EF%2525252525BB%2525252525BF%2525252525E2%252525252580%25252525258B%2525252525EF%2525252525BB%2525252525BF+maxPrice%25252525EF%25252525BB%25252525BF%25252525E2%2525252580%252525258B%25252525EF%25252525BB%25252525BF+maxPrice%252525EF%252525BB%252525BF%252525E2%25252580%2525258B%252525EF%252525BB%252525BF+maxPrice%2525EF%2525BB%2525BF%2525E2%252580%25258B%2525EF%2525BB%2525BF+as_oq+qs) | [Inspect desktop](https://serpapi.com/searches/684fa12e3d06ea30328d73e2/inspect) | [Inspect mobile](https://serpapi.com/searches/684fa1a2ab28c624b11869fe/inspect)

**Comment by schaferyan** [comment]
Another high volume customer to notify:

[Front](https://app.frontapp.com/open/msg_2s53deak?key=arFgHU0lY0PQFlDrlPe4xvHilQUzuP3K)
