### ISSUE TITLE
[Google Maps API] Valid searches not returning results

### ISSUE THREAD

**Issue by arunzone** [serpapi/public-roadmap#2648]
Empty result with error message

<img width="1015" alt="Image" src="https://github.com/user-attachments/assets/288f7d59-036a-4e0e-8185-bf507fd9f963" />
<img width="1499" alt="Image" src="https://github.com/user-attachments/assets/56bcaaca-36da-4ad1-a88b-d6a75c2e96b7" />

<img width="1500" alt="Image" src="https://github.com/user-attachments/assets/0602d68a-4eda-48ea-9c54-b128f30be16c" />

I searched with query "Takeaway under $20" using the `ll=@-37.86380642351989,145.1475484164928,16z` I get empty results
WhenI do the same in google map I get good results .

Public links: 
Serpapi: https://serpapi.com/playground?engine=google_maps&q=takeaway+under+%2420&ll=%40-37.86380642351989%2C145.1475484164928%2C16z&hl=en&type=search&newPara=gl+gl=au

Google: https://www.google.com/maps/search/takeaway+under+$20/@-37.8660416,145.1486213,15z/data=!3m1!4b1?entry=ttu&g_ep=EgoyMDI1MDQyMS4wIKXMDSoASAFQAw%3D%3D

Less gps resolution:
Serpapi: https://serpapi.com/playground?engine=google_maps&q=takeaway+under+%2420&ll=%40-37.8660416%2C145.1486213%2C15z&hl=en&type=search&newPara=gl+gl=au
Google: https://serpapi.com/playground?engine=google_maps&q=takeaway+under+%2420&ll=%40-37.8660416%2C145.1486213%2C15z&hl=en&type=search&newPara=gl+gl=au

**Comment by marm123** [comment]
Thank you for reporting the issue @arunzone. Based on your screenshots, I can see the results were not returned. However, I ran your query now, and it looks to be working:

16z:
<img width="1502" alt="Image" src="https://github.com/user-attachments/assets/d88ff450-50f9-4a14-b4cb-7eb7b1a89c8e" />

15z:
<img width="1502" alt="Image" src="https://github.com/user-attachments/assets/79bc3f42-bac6-47d0-bbb5-76bd3bdb9157" />

I'm not quite sure what might have been causing the query to not return any results, but can you double-check if the results are good on your end as well? I'll keep the thread open for now, but if it's no longer reproducible, we'll close it.

**Comment by hilmanski** [comment]
A high-volume customer reported this. It happened since November 5:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/215471635787159?view=List)

[Inspect](https://serpapi.com/searches/b8341c9478c592ff/690c26483882c524ee6cc67a.json)

@ocvit can you please take a look in case this is related to our recent update? Thanks. LMK if I should create a separate report from the original thread. Ref: https://github.com/serpapi/public-roadmap/issues/73

**Comment by hilmanski** [comment]
TYVM, @ocvit !

**Comment by hilmanski** [comment]
User/Customer reports:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/215471654061909?view=List)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/215471654101687?view=List) - [Maps Place API Inspect](https://serpapi.com/searches/690d89b018dc93ebe92419d6/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/215471654063812?view=List) - [Maps Place Inspect](https://serpapi.com/searches/690d700452acc663d130b685/inspect)

**Comment by jbcoventry** [comment]
Appears to now be every Google Maps search.

**Comment by zyc9012** [comment]
We've released a fix. It's working now.

<img width="890" height="743" alt="Image" src="https://github.com/user-attachments/assets/5a63bc98-6e38-44b5-a5d6-f948627bc295" />

**Comment by marm123** [comment]
I'm reopening that since the customer reported they are still facing this issue (although less frequently), and I've been able to recreate it.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/215471641460506?view=List)
[Inspect - successful](https://serpapi.com/searches/690e0f40217ade23a3d7c3a9/inspect) | [Inspect - failed](https://serpapi.com/searches/690e0f42ae39f389034d056e/inspect)
[Inspect 1 - customer](https://serpapi.com/searches/690e0464de1f337ab65ddba7/inspect) | [Inspect 2 - customer](https://serpapi.com/searches/690e0962484c091ff7844df6/inspect)

**Comment by jbcoventry** [comment]
Another customer still facing this issue, also with decreased frequency.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/215471635787159#part_id=comment-215471635787159-33593730426)

[Search Inspect](https://serpapi.com/searches/690effb1998aad33d6df0ee6/inspect)
[Search Inspect](https://serpapi.com/searches/690effaf703f171efd06f838/inspect)

I checked some recent searches and it appears to be happening for ~1/60 searches.

**Comment by ocvit** [comment]
Here is the current fail numbers per query (1k searches):

| query | run 1 | run 2 |
|---|---|---|
| Playground example | `0` | `1` |
| Aleef Cafe ([ref](https://github.com/serpapi/public-roadmap/issues/2648#issuecomment-3503194105)) | `2` | `0` |
| JP query ([ref](https://github.com/serpapi/public-roadmap/issues/2648#issuecomment-3509379050)) | `0` | `0` |

It doesn't look like a global problem. I think there is at least one kind of server error response that we don't properly retry that leads to empty search results.

**Comment by ocvit** [comment]
We have released a fix. [Empty results](https://github.com/serpapi/public-roadmap/issues/2648#issuecomment-3510378564) do not appear anymore.

**Comment by ocvit** [comment]
We released a series of fixes that improves search results coverage. All the queries that were still affected return correct results now.

@arunzone there can be incompatibilities between specific coords and queries. Your first SerpApi example included coordinates that didn't match the ones from Google URL - `@-37.86380642351989,145.1475484164928,16z` vs `@-37.8660416,145.1486213,15z`. If you try Google's ones you'll get the search results:

<img width="1523" height="1188" alt="Image" src="https://github.com/user-attachments/assets/9d6f1c70-695d-414b-9660-6a149d533997" />

If you try `@-37.86380642351989,145.1475484164928,16z` but with slightly different query, e.g. `takeaway under $21`, you'll also get the results:

<img width="1518" height="1183" alt="Image" src="https://github.com/user-attachments/assets/4778a74b-c9cf-47fa-b31e-6e823b181b27" />
