### ISSUE TITLE
Bug when verifying cell phone number

### ISSUE THREAD

**Issue by Sagac137** [serpapi/public-roadmap#757]
I am performing a user on the serpapi website and asks for confirmation of the cell phone number
When I change the country from +1 (USA) to +55 (Brazil) I put my number with an area code or not (both give an error)
Example
(11)123456789
or
11123456789
(both cases selected area Brazil)
the error is
"Unknown Error. Please contact support."
Written in Red Box

**Comment by BlueKiji77** [comment]
Hello I am facing a similar issue where I enter my correct number but the interface tells me it is invalid.

**Comment by Ehsanul-Karim-Pappu** [comment]
I’m experiencing the same issue with the phone verification process when signing up for the free plan. While email verification works without any problem, the phone verification step consistently fails with the error:

> “Error. The phone verification process was unsuccessful. Please contact support.”

I’ve tested entering my number with the full international format (+880…) as well as without the country code, but neither option resolves the issue. I’m based in Bangladesh, and my phone number is correct.

Could someone please look into this or suggest any workarounds? Thank you!

**Comment by marm123** [comment]
@Ehsanul-Karim-Pappu @umairsiddique3171 If the issue is still appearing for you, can you reach out to us through contact@serpapi.com or directly through chat at https://serpapi.com/? Our Customer Success team will be happy to assist you with the activation.

**Comment by umairsiddique3171** [comment]
Thank you so much! My issue has been resolved, and my profile has been
successfully verified manually. Regards.

**Comment by iyedGrs** [comment]
still having an issue , country : tunisia 
i can not verify the phone number

**Comment by hilmanski** [comment]
Hi @iyedGrs. We're sorry for the inconvenience. Please contact us via contact@serpapi.com.

**Comment by AmratKukreja** [comment]
I'm encountering an issue with the phone verification process while signing up for the free plan. Although email verification works fine, the phone verification consistently fails, displaying the error:

"Error. The phone verification process was unsuccessful. Please contact support."

I've tried entering my phone number in both the full international format (+880…) and without the country code, but neither option resolves the issue. I'm based in Bangladesh, and my phone number is correct.

Could someone look into this or suggest any possible workarounds? Thanks!

**Comment by NateSkiles** [comment]
Hi @AmratKukreja, very sorry for any inconvenience. Can you please reach out to contact@serpapi.com for assistance with this? Alternatively, you can contact us via chat from your account dashboard.

**Comment by Shazil-55** [comment]
I am encountring this issue on registering , my country is Pakistan

**Comment by marm123** [comment]
Hi @Shazil-55, thank you for the message. Can you contact us at contact@serpapi.com? We'll be happy to help you.

**Comment by schaferyan** [comment]
Hi @coyotefreman, thanks for letting us know. I've responded to your email - this should be resolved. Feel free to follow-up there if you have any other questions or if there is anything else we can help you with.

**Comment by ErajT** [comment]
same issue, cant verify my phone number

**Comment by hilmanski** [comment]
Thanks @ErajT @Koudous13. Sure, feel free to reach out to contact@serpapi.com. We'll help from there!

**Comment by hilmanski** [comment]
@mareyam Thanks! Let us know if you need anything else in the email thread.
