### ISSUE TITLE
[Apple App Store Reviews API] No results returned for some desktop `product_id` searches

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#939]
One of our users reported that we provide the `next` key for the last page of reviews, even though the following page returns no results. After investigating the issue, it looks like the reviews should be returned for the following page, but sometimes they are not. Below are examples of the API call with the same parameters:

An API call with results:
<img width="1097" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/76b165b0-69e3-46a4-8d4c-511d5cb3ce71">

API call without results:
<img width="1095" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/9ec2831a-da82-4202-a0d5-4deb617d459b">

[Playground (tested with no_cache=True)](https://serpapi.com/playground?engine=apple_reviews&product_id=1484402218&country=us&page=4&no_cache=true)
[Inspect - with results
](https://serpapi.com/searches/648c1e24e815afd1d090355f/inspect)[Inspect - with results](https://serpapi.com/searches/648c1e175f2203ac58b21989/inspect)
[Inspect - with results
](https://serpapi.com/searches/648c1e21969c08ddac5b67f3/inspect)[Inspect - with no results](https://serpapi.com/searches/648c1d359c84ac1854330780/inspect)
[Inspect - with no results](https://serpapi.com/searches/648c1e1ed5b1c54480af48b2/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000042923)

**Comment by marm123** [comment]
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000042923)

**Comment by kagermanov27** [comment]
Resolved by https://github.com/serpapi/SerpApi/pull/3933

**Comment by marm123** [comment]
I'm reopening as the customer reported the issue is back:

Customer search:
<img width="1094" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/719a5af7-e0aa-426c-8ee0-576e25a0fb18">

The same search in our Playground:
<img width="1440" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/24977674-7ed8-4398-9f7d-098c9e4a2652">

[Playground](https://serpapi.com/playground?engine=apple_reviews&product_id=953286746&country=us&page=16&sort=mostrecent) | [Inspect](https://serpapi.com/searches/64a3d6225f2203709eae655d/inspect)
[Customer Inspect 1](https://serpapi.com/searches/64a3d459f21801bfca289324/inspect) | [Customer Inspect 2](https://serpapi.com/searches/64a3d3c5a1b4239ac7739899/inspect)
[Intercom
](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000043905?view=List)

**Comment by kagermanov27** [comment]
Just some insight:

The latest erroring customer search is a Mac app:

https://apps.apple.com/us/app/id953286746
